[cmake] Use -DWITH_CASE instead of -DCROCO_CASE

diff --git a/OCEAN/jobcomp b/OCEAN/jobcomp
--- a/OCEAN/jobcomp
+++ b/OCEAN/jobcomp
@@ -36,7 +36,7 @@ echo "OPERATING SYSTEM IS: $OS"
 #
 # compiler options
 #
-FC=nvfortran
+FC=gfortran
 
 # if the name of the compiler is specified in the default environment
 if [ -v CROCO_FC ]; then
@@ -107,7 +107,6 @@ ls ${SOURCE}/*.F90             > /dev/null  2>&1 && \cp ${SOURCE}/*.F90 $SCRDIR
 ls ${SOURCE}/*.h               > /dev/null  2>&1 && \cp ${SOURCE}/*.h   $SCRDIR
 ls ${SOURCE}/*.py              > /dev/null  2>&1 && \cp ${SOURCE}/*.py   $SCRDIR
 ls ${SOURCE}/Make*             > /dev/null  2>&1 && \cp ${SOURCE}/Make* $SCRDIR
-ls ${SOURCE}/psyclone.rules.lst >/dev/null  2>&1 && \cp ${SOURCE}/psyclone.rules.lst $SCRDIR
 ls ${SOURCE}/jobcomp           > /dev/null  2>&1 && \cp ${SOURCE}/jobcomp $SCRDIR
 ls ${SOURCE}/amr.in            > /dev/null  2>&1 && \cp ${SOURCE}/amr.in $SCRDIR
 ls ${AGRIF_SRC}                > /dev/null  2>&1 && \cp -r ${AGRIF_SRC} $SCRDIR
@@ -116,10 +115,7 @@ ls ${ROOT_DIR}/PISCES/*        > /dev/null  2>&1 && \cp -r ${ROOT_DIR}/PISCES/* 
 ls ${ROOT_DIR}/PISCES/SED/*    > /dev/null  2>&1 && \cp ${ROOT_DIR}/PISCES/SED/* $SCRDIR
 ls ${ROOT_DIR}/PISCES/kRGB61*  > /dev/null  2>&1 && \cp ${ROOT_DIR}/PISCES/kRGB61* $RUNDIR
 ls ${ROOT_DIR}/MUSTANG/*       > /dev/null  2>&1 && \cp -r ${ROOT_DIR}/MUSTANG/* $SCRDIR
-ls ${ROOT_DIR}/PSYCLONE >/dev/null  2>&1 && \cp -r ${ROOT_DIR}/PSYCLONE $SCRDIR
-
-# TODO: tmp to remove when finished
-sed -e 's/.no-acc.preprocessed/.noa-acc.cpp-done-loops-mpc/g' -i Compile/PSYCLONE/psyclone.rules.lst
+ls ${ROOT_DIR}/PSYCLONE        >/dev/null  2>&1  && \cp -r ${ROOT_DIR}/PSYCLONE $SCRDIR
 
 if [[ -e "namelist_pisces_ref" ]] ; then
         echo "  file namelist_pisces exists in Run directory"
@@ -216,10 +212,14 @@ fi
 
 #
 # Use PSyClone to generate the OpenACC version
-# Need to swtich to the other Makedefs
+# Need to switch to the other Makedefs
 #
-if $($CPP1 testkeys.F | grep -i -q openaccdefined) ; then
+if $($CPP1 testkeys.F | grep -i -q openaccisdefined) ; then
 	cp -f Makedefs.generic.PSYCLONE Makedefs.generic
+	if [[ $FC != 'nvfortran' ]]; then
+		echo "FATAL : Invalid OpenACC compiler, should be FC=nvfortran for now !" 1>&2
+		exit 1
+	fi
 fi
 
 #
